{% set name = "pynormaliz" %}
{% set version = "2.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyNormaliz-{{ version }}.tar.gz
  sha256: 79498bbc6472190d01c98ed62c51d43eb32e5429b266a2090e6962bd0a017b6a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - boost-cpp
    - normaliz
    - python
  run:
    - python

test:
  imports:
    - PyNormaliz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Normaliz/PyNormaliz
  summary: An interface to Normaliz
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - isuruf
