{% set name = "pynormaliz" %}
{% set version = "2.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ef392d0f04e8f41d8eb593c2a8ff1434ea6ae5b379633d44d4bc47068ed5e43

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - libboost-headers
    - normaliz >=3.10.2
    - python
  run:
    - python

test:
  imports:
    - PyNormaliz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Normaliz/PyNormaliz
  summary: An interface to Normaliz
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
