{% set name = "pynormaliz" %}
{% set version = "2.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyNormaliz-{{ version }}.tar.gz
  sha256: ed2943c82b4605eec3500340a694b8f8aeb67e81cd2e0e3305e6779fbfef8d15

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - libboost-headers
    - normaliz >=3.10.2
    - python
  run:
    - python

test:
  imports:
    - PyNormaliz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Normaliz/PyNormaliz
  summary: An interface to Normaliz
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
