{% set name = "pynormaliz" %}
{% set version = "2.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyNormaliz-{{ version }}.tar.gz
  sha256: 359218cf35f400c43f338a132b7887f6a2affb05057c4e7eaa315a9f2b6a8b39

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - libboost-headers
    - normaliz
    - python
  run:
    - python

test:
  imports:
    - PyNormaliz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Normaliz/PyNormaliz
  summary: An interface to Normaliz
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - isuruf
